/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClassificadosIndexRouteImport } from './routes/classificados.index'
import { Route as ClassificadosNovoRouteImport } from './routes/classificados.novo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificadosIndexRoute = ClassificadosIndexRouteImport.update({
  id: '/classificados/',
  path: '/classificados/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificadosNovoRoute = ClassificadosNovoRouteImport.update({
  id: '/classificados/novo',
  path: '/classificados/novo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classificados/novo': typeof ClassificadosNovoRoute
  '/classificados/': typeof ClassificadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classificados/novo': typeof ClassificadosNovoRoute
  '/classificados': typeof ClassificadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classificados/novo': typeof ClassificadosNovoRoute
  '/classificados/': typeof ClassificadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/classificados/novo' | '/classificados/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/classificados/novo' | '/classificados'
  id: '__root__' | '/' | '/classificados/novo' | '/classificados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassificadosNovoRoute: typeof ClassificadosNovoRoute
  ClassificadosIndexRoute: typeof ClassificadosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificados/': {
      id: '/classificados/'
      path: '/classificados'
      fullPath: '/classificados/'
      preLoaderRoute: typeof ClassificadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificados/novo': {
      id: '/classificados/novo'
      path: '/classificados/novo'
      fullPath: '/classificados/novo'
      preLoaderRoute: typeof ClassificadosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassificadosNovoRoute: ClassificadosNovoRoute,
  ClassificadosIndexRoute: ClassificadosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
